
services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  dev-backend:
    build: ./backend/dev
    container_name: dev-backend
    env_file:
      - ./backend/dev/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  prod-backend:
    build: ./backend/prod
    container_name: prod-backend
    env_file:
      - ./backend/prod/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - dev-backend
      - prod-backend
